services:
  db:
    image: postgres:15
    container_name: project_management_dbs
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_management
    ports:
      - '5433:5432'
    volumes:
      - project_management_data:/var/lib/postgresql/data

volumes:
  project_management_data:
